# /modules/custom/world/config/schema/world.schema.yml
world.settings:
  type: config_object
  label: 'World config'
  mapping:
    count:
      type: text
      label: 'Countries Count'
    countries:
      type: text
      label: 'Countries'
      
